services:
  vod-manager:
    image: ghcr.io/jstevenscl/vod-manager:latest
    container_name: vod-manager
    restart: unless-stopped
    ports:
      - "8282:8282"
    volumes:
      - vod_manager_data:/app/data

volumes:
  vod_manager_data:
